const types = {
    /**
     * AUTH
     */
    // LOGIN
    LOGIN_START: 'LOGIN_START',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_ERROR: 'LOGIN_ERROR',
    // LOGOUT
    LOGOUT_START: 'LOGOUT_START',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_ERROR: 'LOGOUT_ERROR',

    /**
     * POSTS
     */
    // GET_POSTS
    GET_POSTS_START: 'GET_POSTS_START',
    GET_POSTS_SUCCESS: 'GET_POSTS_SUCCESS',
    GET_POSTS_ERROR: 'GET_POSTS_ERROR',
    // WRITE NEW POST
    NEW_POST_TITLE: 'NEW_POST_TITLE',
    NEW_POST_TAGS: 'NEW_POST_TAGS',
    NEW_POST_BANNER: 'NEW_POST_BANNER',
    NEW_POST_DESC: 'NEW_POST_DESC',
    NEW_POST_CONTENT: 'NEW_POST_CONTENT',
    NEW_POST_MEDIA: 'NEW_POST_MEDIA',
    // PUBLISH NEW POST
    PUBLISH_POSTS_START: 'PUBLISH_POSTS_START',
    PUBLISH_POSTS_SUCCESS: 'PUBLISH_POSTS_SUCCESS',
    PUBLISH_POSTS_ERROR: 'PUBLISH_POSTS_ERROR',
    // BANNER OFR NEW POST
    BANNER_POSTS_START: 'BANNER_POSTS_START',
    BANNER_POSTS_SUCCESS: 'BANNER_POSTS_SUCCESS',
    BANNER_POSTS_ERROR: 'BANNER_POSTS_ERROR',
    // SINGLE POST
    GET_SINGLE_POST_START: 'GET_SINGLE_POST_START',
    GET_SINGLE_POST_SUCCESS: 'GET_SINGLE_POST_SUCCESS',
    GET_SINGLE_POST_ERROR: 'GET_SINGLE_POST_ERROR',
};

export default types;
